<?php

return [
    'all_cities' => [
        'Caracas',
        'Los Teques',
        'Guarenas',
        'Guatire',
        'Baruta',
        'Chacao',
        'El Hatillo',
        'Petare',
        'Los Dos Caminos',
        'La Guaira',
        'Maracaibo',
        'Cabimas',
        'Ciudad Ojeda',
        'Machiques',
        'Santa Bárbara del Zulia',
        'San Francisco',
        'Lagunillas (Zulia)',
        'Valencia',
        'Puerto Cabello',
        'Guacara',
        'Naguanagua',
        'San Diego',
        'Los Guayos',
        'Bejuma',
        'Mariara',
        'Maracay',
        'La Victoria',
        'Turmero',
        'Cagua',
        'Villa de Cura',
        'El Limón',
        'Palo Negro',
        'Santa Rita',
        'Barcelona',
        'Puerto La Cruz',
        'Lechería',
        'El Tigre',
        'Anaco',
        'Cantaura',
        'Clarines',
        'San Cristóbal',
        'San Antonio del Táchira',
        'Rubio',
        'Táriba',
        'La Fría',
        'Colón',
        'San Juan de Colón',
        'Barquisimeto',
        'Carora',
        'Quíbor',
        'El Tocuyo',
        'Cabudare',
        'Duaca',
        'Mérida',
        'Ejido',
        'Tovar',
        'El Vigía',
        'Santa Cruz de Mora',
        'Lagunillas (Mérida)',
        'Ciudad Guayana',
        'Puerto Ordaz',
        'San Félix',
        'Ciudad Bolívar',
        'Upata',
        'Caicara del Orinoco',
        'Tumeremo',
        'Cumaná',
        'Carúpano',
        'Güiria',
        'Araya',
        'Cariaco',
        'Porlamar',
        'La Asunción',
        'Juan Griego',
        'Pampatar',
        'El Valle del Espíritu Santo',
        'Maturín',
        'Punta de Mata',
        'Temblador',
        'Caripito',
        'Barrancas del Orinoco',
        'Coro',
        'Punto Fijo',
        'Tucacas',
        'Chichiriviche',
        'Dabajuro',
        'La Vela de Coro',
        'Barinas',
        'Barinitas',
        'Socopó',
        'Santa Bárbara',
        'Guanare',
        'Acarigua',
        'Araure',
        'Biscucuy',
        'Valera',
        'Trujillo',
        'Boconó',
        'Sabana de Mendoza',
        'San Felipe',
        'Yaritagua',
        'Nirgua',
        'Chivacoa',
        'San Carlos',
        'Tinaco',
        'El Pao',
        'San Juan de los Morros',
        'Calabozo',
        'Valle de la Pascua',
        'Zaraza',
        'Altagracia de Orituco',
        'San Fernando de Apure',
        'Biruaca',
        'Achaguas',
        'Tucupita',
        'Puerto Ayacucho',
        'Catia La Mar',
        'Maiquetía',
        'Macuto',
        'Naiguatá',
    ],
];
